#!/usr/bin/env python3
"""Build index.html — a single-file Kindle-style reader for everything in library/.

Usage:  python3 tools/build-reader.py

No configuration needed. The script discovers content from the folder structure
(Next.js-style routing):

    library/
      <section>/            first-level folder  = a shelf section in the library
        section.json        optional: {"title": "..."}
        <book>/             second-level folder = one book
          book.json         optional: {"title", "author", "description"}
          01-intro.md       .md files, sorted by filename = chapters
          <part>/           deeper folders = named parts; their .md files are
                            chapters grouped under a part heading in the TOC
        loose-note.md       a loose .md directly in a section = a one-chapter book

Ordering: natural sort of file/folder names. A leading "NN-" numeric prefix
controls order and is stripped from display titles. Chapter titles come from
the first "# H1" line of the file, falling back to the prettified filename.

Re-run any time you add or edit markdown files. Output: index.html (repo root).
"""
import base64
import json
import os
import re
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
LIBRARY = os.path.join(ROOT, "library")
OUT = os.path.join(ROOT, "index.html")
SW_OUT = os.path.join(ROOT, "sw.js")
MANIFEST_OUT = os.path.join(ROOT, "manifest.webmanifest")

# Bump this when sw.js changes so old caches are discarded on next visit.
OFFLINE_CACHE = "library-offline-v3"

# The service worker: network-first (online readers always get fresh content),
# with a cache fallback so the live-link URL opens with no connection. Because
# the whole library is embedded in index.html, caching that one document makes
# every book available offline. Only runs over http(s) — a no-op on file://.
SERVICE_WORKER = """\
/* Auto-generated by tools/build-reader.py — do not edit by hand. */
const CACHE = "%(cache)s";
const CORE = ["./", "./index.html", "./manifest.webmanifest"];

self.addEventListener("install", e => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    await Promise.allSettled(CORE.map(u => c.add(new Request(u, {cache: "reload"}))));
    self.skipWaiting();
  })());
});

self.addEventListener("activate", e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    try {
      const fresh = await fetch(req);
      if (fresh && fresh.ok && req.url.startsWith(self.location.origin)) {
        cache.put(req, fresh.clone());
      }
      return fresh;
    } catch (err) {
      const cached = await cache.match(req, {ignoreSearch: true});
      if (cached) return cached;
      if (req.mode === "navigate") {
        return (await cache.match("./index.html")) || (await cache.match("./")) || Response.error();
      }
      return Response.error();
    }
  })());
});
""" % {"cache": OFFLINE_CACHE}

# An open-book glyph, drawn as an SVG so no binary asset is needed.
_ICON_SVG = (
    "<svg xmlns='http://www.w3.org/2000/svg' width='512' height='512'>"
    "<rect width='512' height='512' rx='110' fill='#b3762f'/>"
    "<g fill='none' stroke='#fff' stroke-width='26' stroke-linecap='round' stroke-linejoin='round'>"
    "<path d='M256 152 C210 122 150 122 120 140 L120 372 C150 354 210 354 256 384'/>"
    "<path d='M256 152 C302 122 362 122 392 140 L392 372 C362 354 302 354 256 384'/>"
    "<line x1='256' y1='152' x2='256' y2='384'/></g></svg>"
)


def natural_key(name):
    """'10-foo' sorts after '2-bar': split digit runs and compare numerically."""
    return [int(p) if p.isdigit() else p.lower() for p in re.split(r"(\d+)", name)]


def prettify(name):
    """Folder/file name -> display title: strip 'NN-' prefix, dashes -> spaces, Title Case."""
    name = re.sub(r"^\d+[-_. ]+", "", name)
    words = re.split(r"[-_]+", name)
    return " ".join(w[:1].upper() + w[1:] for w in words if w)


def title_of(md, fallback):
    for line in md.splitlines():
        m = re.match(r"#\s+(.*)", line)
        if m:
            return m.group(1).strip()
    return fallback


WARNINGS = []


def warn(msg):
    WARNINGS.append(msg)
    print(f"  ! {msg}")


def lint_chapter(relpath, md):
    """Warn about content the reader can't display well (items 7 & 9)."""
    if not re.search(r"^#\s+\S", md, re.M):
        warn(f"{relpath}: no '# Title' H1 — TOC will show the prettified filename")
    body = re.sub(r"```[\s\S]*?```", "", md)  # ignore code blocks
    if re.search(r"!\[[^\]]*\]\(", body):
        warn(f"{relpath}: contains images (![...]) — the reader does not render images")
    if re.search(r"\[\^", body):
        warn(f"{relpath}: contains footnotes ([^...]) — not supported by the reader")
    if re.search(r"^ {4,}([-*+]|\d+[.)])\s", body, re.M):
        warn(f"{relpath}: list nested deeper than one level — deeper levels render flattened")


def lint_prefixes(dirpath, names):
    """Two '03-...' entries in one folder sort by the rest of the name — usually a mistake."""
    seen = {}
    for name in names:
        m = re.match(r"^(\d+)[-_. ]", name)
        if not m:
            continue
        key = int(m.group(1))
        if key in seen:
            rel = os.path.relpath(dirpath, ROOT)
            warn(f"{rel}: duplicate numeric prefix {m.group(1)!r} on {seen[key]!r} and {name!r}")
        else:
            seen[key] = name


def read_json(path):
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    return {}


def list_entries(dirpath):
    """(files, dirs) — visible entries, natural-sorted."""
    files, dirs = [], []
    for name in sorted(os.listdir(dirpath), key=natural_key):
        if name.startswith("."):
            continue
        full = os.path.join(dirpath, name)
        (dirs if os.path.isdir(full) else files).append(name)
    return files, dirs


def collect_book_chapters(book_dir, book_id, chapters):
    """Walk a book folder; append chapter dicts to `chapters`, return their indices.

    Files and subfolders at each level are processed in one natural-sorted pass,
    so a '05-part-two/' folder can be ordered between chapter files. Nested
    folders become part labels ('Categories', 'Part Two / Basics', ...).
    """
    indices = []

    def walk(dirpath, part_label):
        entries = sorted(os.listdir(dirpath), key=natural_key)
        lint_prefixes(dirpath, [e for e in entries if not e.startswith(".")])
        for name in entries:
            if name.startswith("."):
                continue
            full = os.path.join(dirpath, name)
            if os.path.isdir(full):
                sub = prettify(name)
                walk(full, f"{part_label} / {sub}" if part_label else sub)
            elif name.endswith(".md"):
                with open(full, encoding="utf-8") as fh:
                    md = fh.read()
                lint_chapter(os.path.relpath(full, ROOT), md)
                indices.append(len(chapters))
                chapters.append({
                    "id": os.path.relpath(full, ROOT).replace(os.sep, "/"),
                    "file": name,
                    "book": book_id,
                    "part": part_label,
                    "num": len(indices),
                    "title": title_of(md, prettify(os.path.splitext(name)[0])),
                    "md": md,
                })

    walk(book_dir, "")
    return indices


ACCESS_CONFIG = os.path.join(TOOLS, "access-config.json")


def load_access_token():
    """Optional site-lock token, checked in order:
    1. SITE_ACCESS_TOKEN env var (how CI supplies it, from a repo secret —
       keeps the token out of the public repo entirely).
    2. tools/access-config.json ({"token": "..."}) for local builds — gitignored.
    Absent both = gating disabled, site is fully open (the default)."""
    env_token = (os.environ.get("SITE_ACCESS_TOKEN") or "").strip()
    if env_token:
        return env_token
    if not os.path.isfile(ACCESS_CONFIG):
        return None
    with open(ACCESS_CONFIG, encoding="utf-8") as fh:
        return (json.load(fh).get("token") or "").strip() or None


def build():
    if not os.path.isdir(LIBRARY):
        sys.exit(f"No library/ folder found at {LIBRARY} — nothing to build.")

    sections = []
    chapters = []  # flat, global list; books reference chapters by index

    sec_files, sec_dirs = list_entries(LIBRARY)
    for stray in sec_files:
        print(f"  ! ignoring {stray} at library/ root — put .md files inside a section folder")

    for sec_name in sec_dirs:
        sec_dir = os.path.join(LIBRARY, sec_name)
        sec_meta = read_json(os.path.join(sec_dir, "section.json"))
        section = {"id": sec_name, "title": sec_meta.get("title", prettify(sec_name)), "books": []}

        files, dirs = list_entries(sec_dir)

        # loose .md files directly in a section: each becomes a one-chapter book
        for fname in files:
            if not fname.endswith(".md"):
                continue
            with open(os.path.join(sec_dir, fname), encoding="utf-8") as fh:
                md = fh.read()
            lint_chapter(f"library/{sec_name}/{fname}", md)
            stem = os.path.splitext(fname)[0]
            book_id = f"{sec_name}/{stem}"
            idx = len(chapters)
            chapters.append({
                "id": f"library/{sec_name}/{fname}",
                "file": fname,
                "book": book_id,
                "part": "",
                "num": 1,
                "title": title_of(md, prettify(stem)),
                "md": md,
            })
            section["books"].append({
                "id": book_id,
                "title": title_of(md, prettify(stem)),
                "author": "",
                "description": "",
                "chapters": [idx],
            })

        # folders in a section: each is a book
        for book_name in dirs:
            book_dir = os.path.join(sec_dir, book_name)
            meta = read_json(os.path.join(book_dir, "book.json"))
            book_id = f"{sec_name}/{book_name}"
            ch_idx = collect_book_chapters(book_dir, book_id, chapters)
            if not ch_idx:
                print(f"  ! skipping empty book folder library/{sec_name}/{book_name}")
                continue
            section["books"].append({
                "id": book_id,
                "title": meta.get("title", prettify(book_name)),
                "author": meta.get("author", ""),
                "description": meta.get("description", ""),
                "chapters": ch_idx,
            })

        if section["books"]:
            sections.append(section)

    with open(os.path.join(TOOLS, "reader-template.html"), encoding="utf-8") as fh:
        tpl = fh.read()

    # "</" would terminate the <script> tag early; "<\/" is a safe JS escape.
    def embed(obj):
        return json.dumps(obj, ensure_ascii=False).replace("</", "<\\/")

    html = (tpl.replace("__LIB_DATA__", embed(sections))
               .replace("__CHAPTER_DATA__", embed(chapters))
               .replace("__ACCESS_TOKEN__", embed(load_access_token())))

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)

    # PWA companions: the service worker (offline caching) + web app manifest
    # (installable "Add to Home Screen"). Regenerated every build to stay in sync.
    with open(SW_OUT, "w", encoding="utf-8") as fh:
        fh.write(SERVICE_WORKER)

    icon = "data:image/svg+xml;base64," + base64.b64encode(_ICON_SVG.encode("utf-8")).decode("ascii")
    manifest = {
        "name": "Library",
        "short_name": "Library",
        "start_url": "./",
        "scope": "./",
        "display": "standalone",
        "background_color": "#fafaf7",
        "theme_color": "#fafaf7",
        "icons": [
            {"src": icon, "sizes": "512x512", "type": "image/svg+xml", "purpose": "any"},
            {"src": icon, "sizes": "192x192", "type": "image/svg+xml", "purpose": "maskable"},
        ],
    }
    with open(MANIFEST_OUT, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, ensure_ascii=False, indent=2)

    n_books = sum(len(s["books"]) for s in sections)
    size_kb = len(html.encode("utf-8")) // 1024
    print(f"Wrote {OUT}: {len(sections)} sections, {n_books} books, "
          f"{len(chapters)} chapters, {size_kb} KB")
    print(f"Wrote {SW_OUT} and {MANIFEST_OUT} (offline PWA, cache {OFFLINE_CACHE})")
    if load_access_token():
        print("Site lock is ON (tools/access-config.json) — the bare URL shows a lock screen; "
              "only links containing ?k=<token> (or a browser that already unlocked it) get in.")
    if size_kb > 5 * 1024:
        warn(f"index.html is {size_kb // 1024} MB — page load/parse will start to feel it; "
             "consider splitting rarely-read sections into a second library")
    if WARNINGS:
        print(f"\n{len(WARNINGS)} warning(s) — see '!' lines above.")


def snapshot():
    """mtime fingerprint of everything that feeds the build."""
    stamp = 0.0
    paths = [os.path.join(TOOLS, "reader-template.html"), os.path.abspath(__file__)]
    for dirpath, dirnames, filenames in os.walk(LIBRARY):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        paths.extend(os.path.join(dirpath, f) for f in filenames if not f.startswith("."))
        paths.append(dirpath)
    for p in paths:
        try:
            stamp = max(stamp, os.stat(p).st_mtime)
        except OSError:
            pass
    return (stamp, len(paths))


def serve(port):
    """--serve: build, serve the repo over http, rebuild whenever library/ changes."""
    import http.server
    import threading
    import time

    class Quiet(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *a, **kw):
            super().__init__(*a, directory=ROOT, **kw)

        def log_message(self, *a):
            pass

    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", port), Quiet)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    print(f"\nServing http://127.0.0.1:{port}  (Ctrl-C to stop)")
    print("Watching library/ and the template — rebuilding on change…")
    state = snapshot()
    try:
        while True:
            time.sleep(1)
            now = snapshot()
            if now != state:
                state = now
                print("\nChange detected — rebuilding…")
                del WARNINGS[:]
                try:
                    build()
                except SystemExit as e:
                    print(f"  build failed: {e}")
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    args = sys.argv[1:]
    build()
    if "--serve" in args:
        i = args.index("--serve")
        port = int(args[i + 1]) if i + 1 < len(args) and args[i + 1].isdigit() else 8080
        serve(port)
